image:
- Visual Studio 2017
# - Ubuntu   # waiting for astropy wheel

build: off

stack: python 3

environment:
  PY_DIR: C:\Python36-x64

clone_depth: 3

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%PATH%

install:
- pip install -e .[tests]
  
test_script:
- pytest -sv
