language: python
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
- 3.6

os:
- linux

install: pip install -e .[tests]

matrix:
  include:
  - os: linux
    python: 3.7
    install: pip install -e .[tests,cov]
    script:
    - flake8
    - mypy . --ignore-missing-imports
    after_success:
    - pytest --cov
    - coveralls

script: pytest -rsv
