language: python
sudo: required
dist: xenial
group: travis_latest

git:
  depth: 3
  quiet: true

python:
  - 3.6
# -3.7  # FIXME waiting h5py wheel

os:
  - linux

install: pip install -e .[tests]

script:
  - pytest -sv
  - flake8
#  - mypy . --ignore-missing-imports  # waiting typeshed update

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then
    pytest --cov;
    coveralls;
    fi
