language: python
fast_finish: true

python:
  - 3.6

os:
  - linux

notifications:
  email: false

git:
  depth: 3


install: pip -q install -e .[tests]

script: 
  - pytest
  - coverage run tests/test_all.py -v

after_success: coveralls
