[build-system]
requires = ["setuptools", "wheel",
'python-dateutil','pytz', 'nose','numpy','scipy','xarray', 'h5py',
       'sciencedates',
        'pathvalidate',
'matplotlib', 'seaborn',
'lowtran','transcarread','astropy',
 "nose"] 
